fix: attempt to address TS2339 error
Attempt to address error TS2339 in prisma-session-store.ts: Property 'uid' does not exist on type 'PartialObjectDeep<SessionData>'.